export const previewFilters = [
  { id: 'all', label: '全部方案' },
  { id: 'particle', label: '粒子与 AI' },
  { id: 'robot', label: '机器人' },
  { id: 'motion', label: '动态叙事' },
];

export const reviewOrder = ['gdamon', 'make-it-useful', 'robot'];

export const previews = [
  {
    id: 'oil-matter',
    title: '液态金属 · Matter',
    subtitle: 'Intelligence, taking shape.',
    category: 'motion',
    href: '/oil-lab/matter',
    image: '/preview-assets/oil-matter.webp',
    description: 'OpenRouter 生成的镜面金属从封闭形态展开为雕塑字母 D，接入钴蓝色个人网站与真实研究项目。',
    motion: '金属形态 → 雕塑 D → 研究项目与联系',
    interaction: '原生滚动逐帧推进变形，向上滚动可回看；停下时画面静止，继续向下浏览完整个人网站。',
    tags: ['Oil Motion', '生成式动效', '完整个人站'],
    featured: true,
  },
  {
    id: 'oil-archive',
    title: '玻璃档案 · Archive',
    subtitle: 'An open research practice.',
    category: 'motion',
    href: '/oil-lab/archive',
    image: '/preview-assets/oil-archive.webp',
    description: '半透明玻璃前页随滚动向前移出，搭配米白色编辑排版、真实论文项目与研究笔记入口。',
    motion: '玻璃前页 → 平稳移出 → 研究档案',
    interaction: '向下滚动移出前页，反向滚动归位；通过项目、研究笔记和个人介绍继续探索。',
    tags: ['Oil Motion', 'OpenRouter 生成', '研究档案'],
    featured: true,
  },
  {
    id: 'oil-handoff',
    title: '机械交接 · Handoff',
    subtitle: 'From thinking to doing.',
    category: 'robot',
    href: '/oil-lab/handoff',
    image: '/preview-assets/oil-handoff.webp',
    description: '橙色机械臂在淡紫色微型物流场景里夹起包裹，以生成式动效连接规划、行动和真实供应链项目。',
    motion: '机械臂靠近 → 夹住包裹 → 稳定抬起',
    interaction: '滚动控制机械动作并可反向查看，随后进入供应链智能体、工具调用和领域模型的完整内容。',
    tags: ['Oil Motion', 'OpenRouter 生成', '机械交互'],
    featured: true,
  },
  {
    id: 'make-it-useful',
    title: 'GDamon · 滚动研究叙事',
    subtitle: 'Train models. Deploy agents. Evaluate systems.',
    category: 'motion',
    href: '/film',
    image: '/preview-assets/scroll-story.webp',
    description: '从领域模型训练，到动态工具智能体，再到多轮评估：动画旁持续展示 Damon 的职责、实际项目与工作成果。',
    motion: '训练模型 → 部署智能体 → 评估系统 → 项目案例',
    interaction: '滚动查看训练矩阵、机器人拆装与粒子署名；每章的项目和成果可直接打开完整案例，支持反向回看。',
    tags: ['原生滚动', '实时 3D', '完整个人站'],
    featured: true,
  },
  {
    id: 'gdamon',
    title: 'GDamon · AI 粒子变形',
    subtitle: 'Intelligence, engineered.',
    category: 'particle',
    href: '/kernelcode/index.html',
    image: '/preview-assets/gdamon-research.webp',
    mediaLabel: '研究方法与项目成果',
    description: '从研究方法到生产系统：粒子球体与网络旁展示训练、评估、工具使用和真实项目成果，可直接进入案例。',
    motion: '星尘丝带 → 核心球体 → 神经网络 → GDAMON',
    interaction: '拖拽星尘探索视角；滚动查看方法与案例证据。手机可在章节内继续阅读，案例返回后保留阅读位置。',
    tags: ['研究与成果', '滚动变形', '项目案例'],
    featured: true,
  },
  {
    id: 'core-film',
    title: '机械核心 · 连续装配短片',
    subtitle: 'Inner Workings',
    category: 'motion',
    href: '/motion-lab/core',
    image: '/motion-studies/core-film-poster.webp',
    video: '/motion-studies/core-film.mp4',
    mediaLabel: '连续 3D 短片',
    description: '石墨色机械环拆解为轨道，逐层归位，点亮琥珀色核心。进入页面即可播放完整循环。',
    motion: '拆解 → 环绕 → 装配 → 核心点亮',
    interaction: '播放、暂停、重播或拖动时间轴；可下载完整 MP4。',
    tags: ['连续运动', 'Three.js', 'MP4 短片'],
    featured: true,
  },
  {
    id: 'robot',
    title: '机器人 · Hello, human.',
    subtitle: 'The human behind the agent',
    category: 'robot',
    href: '/robot',
    image: '/preview-assets/robot.webp',
    description: '钴蓝色巨幅标题与白色陶瓷机器人：注视、眨眼、点头，再拆开外壳看处理器，将规划、行动与学习接入真实项目。',
    motion: '机器人苏醒 → 外壳展开 → 核心展示 → 重新组装 → 真实项目',
    interaction: '指针控制视线，Say hello 点头回应；滚动拆开、展示、重组，再连贯进入作品区，向上滚动可回看。',
    tags: ['Three.js 角色', '滚动拆解', '完整个人站'],
    featured: false,
  },
  {
    id: 'matrix',
    title: '数字矩阵 · 代码成形',
    subtitle: 'From signals to systems',
    category: 'particle',
    href: '/particle?scene=matrix',
    image: '/preview-assets/matrix.webp',
    description: '绿色字符雨随滚动汇成 DAMON，再展开为有序的数字系统。',
    motion: '字符雨 → DAMON → 数字系统',
    interaction: '滚动推进三段形态，移动指针扰动字符与视角。',
    tags: ['字符雨', '滚动变形', '完整个人站'],
    featured: false,
  },
  {
    id: 'signature',
    title: '星尘签名 · DAMON',
    subtitle: 'A signature in motion',
    category: 'particle',
    href: '/particle?scene=signature',
    image: '/preview-assets/signature.webp',
    description: '蓝紫色星尘织成五道丝带，聚拢写下 DAMON，再展开为环绕结构。',
    motion: '星尘丝带 → DAMON → 环绕结构',
    interaction: '滚动聚拢或展开星尘，移动指针观察视差与粒子响应。',
    tags: ['星尘签名', '滚动变形', '完整个人站'],
    featured: false,
  },
  {
    id: 'neural',
    title: '神经网络 · 连接成形',
    subtitle: 'Intelligence is connected',
    category: 'particle',
    href: '/particle?scene=neural',
    image: '/preview-assets/neural.webp',
    description: '暖金与青色节点组成空间网络，经由 DAMON 字样重新连接为系统。',
    motion: '节点网络 → DAMON → 连接系统',
    interaction: '滚动重组节点与连线，移动指针改变观察角度。',
    tags: ['节点连线', '滚动变形', '完整个人站'],
    featured: false,
  },
  {
    id: 'tree',
    title: '粒子树 · 生长的智能',
    subtitle: 'A living intelligence',
    category: 'particle',
    href: '/particle?scene=tree',
    image: '/preview-assets/tree.webp',
    description: '蓝色粒子从球体长成树冠，再收拢为带有 Damon 字样的旋转方体。',
    motion: '球体 → 粒子树 → 签名方体',
    interaction: '滚动改变形态与镜头，移动指针观察树冠视差。',
    tags: ['粒子生长', '滚动变形', '完整个人站'],
    featured: false,
  },
];

export const archiveGroups = [
  {
    id: 'collections',
    title: '方案合集与个人内容',
    description: '所有页面共用的个人资料、研究笔记，以及完整实验合集。',
    items: [
      { id: 'oil-lab', title: 'Oil Motion 三个网站', href: '/oil-lab', description: '液态金属、玻璃档案与机械交接的完整合集。' },
      { id: 'motion-lab', title: '动态实验合集', href: '/motion-lab', description: '观察者、机械花与连续装配核心。' },
      { id: 'about', title: '关于 Damon', href: '/about', description: '工作经历、教育背景与研究方向。' },
      { id: 'notes', title: '研究笔记', href: '/blog', description: '论文、智能体与实际开发中的思考。' },
      { id: 'uses', title: '工具与工作环境', href: '/uses', description: '日常研究与工程使用的工具。' },
    ],
  },
  {
    id: 'motion-studies',
    title: 'Oil Motion 与动态实验',
    description: '观察者与机械花保留六帧造型实验；机械核心已升级为连续 3D 短片。',
    items: [
      {
        id: 'observer',
        title: '观察者 · The Observer',
        href: '/motion-lab/observer',
        description: '移动指针，让瓷白机器人在六个观察方向间转头。',
      },
      {
        id: 'bloom',
        title: '机械花 · Soft Intelligence',
        href: '/motion-lab/bloom',
        description: '拖动花朵或时间轴，查看六个逐步展开的姿态。',
      },
      {
        id: 'core',
        title: '机械核心 · Inner Workings',
        href: '/motion-lab/core',
        description: '连续拆解、环绕与装配的机械核心，支持播放控制和 MP4 下载。',
      },
    ],
  },
  {
    id: 'references',
    title: '原始 HTML 参考',
    description: '保留粘贴稿与最初的品牌版本，方便对照。',
    items: [
      { id: 'kernelcode-reference', title: 'KernelCode 原版', href: '/kernelcode/reference.html', description: '摄影首屏、〈K〉体素与球体、键盘、字标粒子。' },
      { id: 'future-machine', title: 'Future Machine 原版', href: '/future-machine.html', description: '蓝色全屏、白色机器人头盔与部件装配入场。' },
      { id: 'anchor-original', title: 'Anchor AI 原版', href: '/html-studies/anchor-original.html', description: '个人化改写之前的粒子树原始 HTML。' },
    ],
  },
  {
    id: 'previous-sites',
    title: '旧版主页与播放器',
    description: '保留之前的完整页面，方便对照新版本。',
    items: [
      { id: 'classic', title: '最初的个人主页', href: '/classic', description: 'Agent OS 导航、能力介绍、项目与笔记。' },
      { id: 'motion', title: '早期动态主页', href: '/motion', description: '之前的个人网站动态排版方案。' },
      { id: 'film-player', title: 'Film 归档播放器', href: '/film?view=player', description: '原来的 18 秒时间轴版本；当前网站版本在 /film。' },
    ],
  },
  {
    id: 'playground',
    title: '交互实验室',
    description: '空间、纸张、档案与信号的四种交互。',
    items: [
      { id: 'observatory', title: '研究展厅', href: '/lab/observatory', description: '滚动推进空间镜头，指针改变观看方向。' },
      { id: 'tactile', title: '纸张工作台', href: '/lab/tactile', description: '拖动纸张边缘，查看卷曲、阴影与回弹。' },
      { id: 'gallery', title: '旋转项目档案', href: '/lab/gallery', description: '旋转并展开档案，支持拖拽、按钮和键盘。' },
      { id: 'signal', title: '信号与噪声', href: '/lab/signal', description: '指针驱动向量场，切换研究阶段重组图形。' },
    ],
  },
  {
    id: 'concepts',
    title: '早期视觉方案',
    description: '最初的三种个人网站视觉方向。',
    items: [
      { id: 'editorial', title: 'Editorial · 编辑排版', href: '/concepts/editorial', description: '钴蓝首屏、大字标题与项目列表。' },
      { id: 'kinetic', title: 'Kinetic · 立体字形', href: '/concepts/kinetic', description: '立体 AGENT 字形与蓝色研究主页。' },
      { id: 'sculpture', title: 'Sculpture · 玻璃雕塑', href: '/concepts/sculpture', description: '浅色页面上的可旋转三维环形雕塑。' },
    ],
  },
  {
    id: 'experiences',
    title: '叙事与空间方案',
    description: '围绕决策路径、研究笔记与世界模型展开的三组页面。',
    items: [
      { id: 'path', title: 'The Agent’s Path', href: '/experiences/path', description: '沿着规划、工具、评估与部署的路径浏览研究。' },
      { id: 'field-notes', title: 'Field Notes', href: '/experiences/field-notes', description: '以研究笔记与工具为线索探索项目。' },
      { id: 'world-model', title: 'World Model', href: '/experiences/world-model', description: '切换规划、工具与评估决策，查看空间中的响应。' },
    ],
  },
];
