export const previewFilters = [
  { id: 'all', label: '全部方案' },
  { id: 'particle', label: '粒子与 AI' },
  { id: 'robot', label: '机器人' },
  { id: 'motion', label: '连续短片' },
];

export const previews = [
  {
    id: 'gdamon',
    title: 'GDamon · AI 粒子变形',
    subtitle: 'Intelligence, engineered.',
    category: 'particle',
    href: '/kernelcode/index.html',
    image: '/preview-assets/gdamon-poster.webp',
    video: '/preview-assets/gdamon-motion.mp4',
    mediaLabel: '星尘与变形实录',
    description: '蓝紫色星尘织成空间丝带，再进入 30,000 个白色粒子构成的研究、系统与个人签名。',
    motion: '星尘丝带 → 核心球体 → 神经网络 → GDAMON',
    interaction: '拖拽星尘探索视角；滚轮、方向键、上下滑动或顶部导航切屏。',
    tags: ['星尘首屏', '滚动变形', '章节导航'],
    featured: true,
  },
  {
    id: 'core-film',
    title: '机械核心 · 连续装配短片',
    subtitle: 'Inner Workings',
    category: 'motion',
    href: '/motion-lab/core',
    image: '/motion-studies/core-film-poster.webp',
    video: '/motion-studies/core-film.mp4',
    mediaLabel: '连续 3D 短片',
    description: '石墨色机械环拆解为轨道，逐层归位，点亮琥珀色核心。进入页面即可播放完整循环。',
    motion: '拆解 → 环绕 → 装配 → 核心点亮',
    interaction: '播放、暂停、重播或拖动时间轴；可下载完整 MP4。',
    tags: ['连续运动', 'Three.js', 'MP4 短片'],
    featured: true,
  },
  {
    id: 'robot',
    title: '机器人 · 装配与拆解',
    subtitle: 'Agent Assembly',
    category: 'robot',
    href: '/robot',
    image: '/preview-assets/robot.webp',
    description: '钴蓝背景上的白色头盔逐片装配，向下滚动时拆开，接入项目、研究与个人介绍。',
    motion: '部件入场 → 头盔装配 → 滚动拆解',
    interaction: '移动指针看分层视差，滚动拆解；可暂停或重播装配。',
    tags: ['机械装配', '分层视差', '完整个人站'],
    featured: false,
  },
  {
    id: 'matrix',
    title: '数字矩阵 · 代码成形',
    subtitle: 'From signals to systems',
    category: 'particle',
    href: '/particle?scene=matrix',
    image: '/preview-assets/matrix.webp',
    description: '绿色字符雨随滚动汇成 DAMON，再展开为有序的数字系统。',
    motion: '字符雨 → DAMON → 数字系统',
    interaction: '滚动推进三段形态，移动指针扰动字符与视角。',
    tags: ['字符雨', '滚动变形', '完整个人站'],
    featured: false,
  },
  {
    id: 'signature',
    title: '星尘签名 · DAMON',
    subtitle: 'A signature in motion',
    category: 'particle',
    href: '/particle?scene=signature',
    image: '/preview-assets/signature.webp',
    description: '蓝紫色星尘织成五道丝带，聚拢写下 DAMON，再展开为环绕结构。',
    motion: '星尘丝带 → DAMON → 环绕结构',
    interaction: '滚动聚拢或展开星尘，移动指针观察视差与粒子响应。',
    tags: ['星尘签名', '滚动变形', '完整个人站'],
    featured: false,
  },
  {
    id: 'neural',
    title: '神经网络 · 连接成形',
    subtitle: 'Intelligence is connected',
    category: 'particle',
    href: '/particle?scene=neural',
    image: '/preview-assets/neural.webp',
    description: '暖金与青色节点组成空间网络，经由 DAMON 字样重新连接为系统。',
    motion: '节点网络 → DAMON → 连接系统',
    interaction: '滚动重组节点与连线，移动指针改变观察角度。',
    tags: ['节点连线', '滚动变形', '完整个人站'],
    featured: false,
  },
  {
    id: 'tree',
    title: '粒子树 · 生长的智能',
    subtitle: 'A living intelligence',
    category: 'particle',
    href: '/particle?scene=tree',
    image: '/preview-assets/tree.webp',
    description: '蓝色粒子从球体长成树冠，再收拢为带有 Damon 字样的旋转方体。',
    motion: '球体 → 粒子树 → 签名方体',
    interaction: '滚动改变形态与镜头，移动指针观察树冠视差。',
    tags: ['粒子生长', '滚动变形', '完整个人站'],
    featured: false,
  },
];

export const archiveGroups = [
  {
    id: 'motion-studies',
    title: 'Oil Motion 与动态实验',
    description: '观察者与机械花保留六帧造型实验；机械核心已升级为连续 3D 短片。',
    items: [
      {
        id: 'observer',
        title: '观察者 · The Observer',
        href: '/motion-lab/observer',
        description: '移动指针，让瓷白机器人在六个观察方向间转头。',
      },
      {
        id: 'bloom',
        title: '机械花 · Soft Intelligence',
        href: '/motion-lab/bloom',
        description: '拖动花朵或时间轴，查看六个逐步展开的姿态。',
      },
      {
        id: 'core',
        title: '机械核心 · Inner Workings',
        href: '/motion-lab/core',
        description: '连续拆解、环绕与装配的机械核心，支持播放控制和 MP4 下载。',
      },
    ],
  },
  {
    id: 'references',
    title: '原始 HTML 参考',
    description: '保留粘贴稿与最初的品牌版本，方便对照。',
    items: [
      { id: 'kernelcode-reference', title: 'KernelCode 原版', href: '/kernelcode/reference.html', description: '摄影首屏、〈K〉体素与球体、键盘、字标粒子。' },
      { id: 'future-machine', title: 'Future Machine 原版', href: '/future-machine.html', description: '蓝色全屏、白色机器人头盔与部件装配入场。' },
      { id: 'anchor-original', title: 'Anchor AI 原版', href: '/html-studies/anchor-original.html', description: '个人化改写之前的粒子树原始 HTML。' },
    ],
  },
  {
    id: 'playground',
    title: '交互实验室',
    description: '空间、纸张、档案与信号的四种交互。',
    items: [
      { id: 'observatory', title: '研究展厅', href: '/lab/observatory', description: '滚动推进空间镜头，指针改变观看方向。' },
      { id: 'tactile', title: '纸张工作台', href: '/lab/tactile', description: '拖动纸张边缘，查看卷曲、阴影与回弹。' },
      { id: 'gallery', title: '旋转项目档案', href: '/lab/gallery', description: '旋转并展开档案，支持拖拽、按钮和键盘。' },
      { id: 'signal', title: '信号与噪声', href: '/lab/signal', description: '指针驱动向量场，切换研究阶段重组图形。' },
    ],
  },
  {
    id: 'concepts',
    title: '早期视觉方案',
    description: '最初的三种个人网站视觉方向。',
    items: [
      { id: 'editorial', title: 'Editorial · 编辑排版', href: '/concepts/editorial', description: '钴蓝首屏、大字标题与项目列表。' },
      { id: 'kinetic', title: 'Kinetic · 立体字形', href: '/concepts/kinetic', description: '立体 AGENT 字形与蓝色研究主页。' },
      { id: 'sculpture', title: 'Sculpture · 玻璃雕塑', href: '/concepts/sculpture', description: '浅色页面上的可旋转三维环形雕塑。' },
    ],
  },
  {
    id: 'experiences',
    title: '叙事与空间方案',
    description: '围绕决策路径、研究笔记与世界模型展开的三组页面。',
    items: [
      { id: 'path', title: 'The Agent’s Path', href: '/experiences/path', description: '沿着规划、工具、评估与部署的路径浏览研究。' },
      { id: 'field-notes', title: 'Field Notes', href: '/experiences/field-notes', description: '以研究笔记与工具为线索探索项目。' },
      { id: 'world-model', title: 'World Model', href: '/experiences/world-model', description: '切换规划、工具与评估决策，查看空间中的响应。' },
    ],
  },
];
